export const memberDemo = {
  tag: "#JVP00GPVJ",
  name: "\\_JAQUAVIAN_/",
  role: "member",
  lastSeen: "20220715T141027.000Z",
  expLevel: 9,
  trophies: 3985,
  arena: {
    id: 54000012,
    name: "Arena 16",
  },
  clanRank: 29,
  previousClanRank: 29,
  donations: 0,
  donationsReceived: 0,
  clanChestPoints: 0,
  currentRaceFame: 0,
  currentRaceDecksUsed: 0,
  currentRaceDecksUsedToday: 0,
  currentRaceBoatAttacks: 0,
  lastRaceFame: 75,
  lastRaceDecksUsed: 1,
  lastRaceBoatAttacks: 1,
  previousRaceFame: "-",
  previousRaceDecksUsed: "-",
  previousRaceBoatAttacks: "-",
};
export const optionsDemo = {
  clanTag: "#YVYYC9QC",
  awayMaxDays: 7,
  awayDangerDays: 3,
  warWeekFame: 1000,
};
export const topValuesDemo = {
  currentRaceTopFame: 800,
  currentRaceTopBoatAttacks: 4,
  currentRaceTopDecksUsed: 16,
  lastRaceTopFame: 2650,
  lastRaceTopBoatAttacks: 16,
  lastRaceTopDecksUsed: 26,
  previousRaceTopFame: 3150,
  previousRaceTopBoatAttacks: 16,
  previousRaceTopDecksUsed: 27,
  donationsGiven: 581,
  donationsReceived: 510,
};
export const indexDemo = 28;
export const warStateDemo = "warDay";
export const membersDemo = [
  {
    tag: "#2VV8CR92Q",
    name: "Não sei jogar",
    role: "coLeader",
    lastSeen: "20220722T132055.000Z",
    expLevel: 14,
    trophies: 6058,
    arena: {
      id: 54000015,
      name: "Master I",
    },
    clanRank: 1,
    previousClanRank: 1,
    donations: 656,
    donationsReceived: 240,
    clanChestPoints: 0,
    currentRaceFame: 1300,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1600,
    lastRaceDecksUsed: 10,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1600,
    previousRaceDecksUsed: 8,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#LV9PCR9L",
    name: "Trainer Man",
    role: "leader",
    lastSeen: "20220722T133704.000Z",
    expLevel: 14,
    trophies: 5954,
    arena: {
      id: 54000014,
      name: "Challenger III",
    },
    clanRank: 2,
    previousClanRank: 2,
    donations: 639,
    donationsReceived: 520,
    clanChestPoints: 0,
    currentRaceFame: 1400,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 2650,
    lastRaceDecksUsed: 16,
    lastRaceBoatAttacks: 2,
    previousRaceFame: 2700,
    previousRaceDecksUsed: 16,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#8CQRV2GPP",
    name: "Bucks",
    role: "coLeader",
    lastSeen: "20220722T130753.000Z",
    expLevel: 14,
    trophies: 5802,
    arena: {
      id: 54000014,
      name: "Challenger III",
    },
    clanRank: 3,
    previousClanRank: 4,
    donations: 180,
    donationsReceived: 200,
    clanChestPoints: 0,
    currentRaceFame: 1000,
    currentRaceDecksUsed: 6,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 900,
    lastRaceDecksUsed: 8,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 2750,
    previousRaceDecksUsed: 16,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#80PGQ0QPQ",
    name: "ShiN",
    role: "elder",
    lastSeen: "20220722T134031.000Z",
    expLevel: 14,
    trophies: 5779,
    arena: {
      id: 54000014,
      name: "Challenger III",
    },
    clanRank: 4,
    previousClanRank: 3,
    donations: 80,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 1150,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 4,
    lastRaceFame: 1750,
    lastRaceDecksUsed: 12,
    lastRaceBoatAttacks: 4,
    previousRaceFame: 2350,
    previousRaceDecksUsed: 16,
    previousRaceBoatAttacks: 4,
  },
  {
    tag: "#Q9GGL2LJ",
    name: "Gin",
    role: "coLeader",
    lastSeen: "20220722T133107.000Z",
    expLevel: 14,
    trophies: 5726,
    arena: {
      id: 54000014,
      name: "Challenger III",
    },
    clanRank: 5,
    previousClanRank: 5,
    donations: 257,
    donationsReceived: 280,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 2200,
    lastRaceDecksUsed: 15,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1800,
    previousRaceDecksUsed: 12,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#2LPU89PL9",
    name: "proteico",
    role: "coLeader",
    lastSeen: "20220722T123819.000Z",
    expLevel: 14,
    trophies: 5675,
    arena: {
      id: 54000014,
      name: "Challenger III",
    },
    clanRank: 6,
    previousClanRank: 6,
    donations: 78,
    donationsReceived: 80,
    clanChestPoints: 0,
    currentRaceFame: 800,
    currentRaceDecksUsed: 7,
    currentRaceDecksUsedToday: 2,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 2600,
    lastRaceDecksUsed: 16,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 2000,
    previousRaceDecksUsed: 17,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#8LQL2LCLY",
    name: "mouratheBale",
    role: "coLeader",
    lastSeen: "20220722T123004.000Z",
    expLevel: 14,
    trophies: 5575,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 7,
    previousClanRank: 9,
    donations: 432,
    donationsReceived: 320,
    clanChestPoints: 0,
    currentRaceFame: 1450,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1050,
    lastRaceDecksUsed: 6,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1300,
    previousRaceDecksUsed: 6,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#98LR8UVC",
    name: "Naifas",
    role: "elder",
    lastSeen: "20220722T130142.000Z",
    expLevel: 14,
    trophies: 5553,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 8,
    previousClanRank: 7,
    donations: 378,
    donationsReceived: 450,
    clanChestPoints: 0,
    currentRaceFame: 950,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 8,
    lastRaceFame: 1750,
    lastRaceDecksUsed: 16,
    lastRaceBoatAttacks: 16,
    previousRaceFame: 1800,
    previousRaceDecksUsed: 16,
    previousRaceBoatAttacks: 16,
  },
  {
    tag: "#JYVLUL9U2",
    name: "fiel",
    role: "member",
    lastSeen: "20220722T081407.000Z",
    expLevel: 12,
    trophies: 5509,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 9,
    previousClanRank: 8,
    donations: 54,
    donationsReceived: 240,
    clanChestPoints: 0,
    currentRaceFame: 700,
    currentRaceDecksUsed: 16,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 900,
    lastRaceDecksUsed: 4,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1800,
    previousRaceDecksUsed: 13,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#9RGY0029",
    name: "The Trooper",
    role: "coLeader",
    lastSeen: "20220722T134636.000Z",
    expLevel: 14,
    trophies: 5491,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 10,
    previousClanRank: 10,
    donations: 209,
    donationsReceived: 280,
    clanChestPoints: 0,
    currentRaceFame: 600,
    currentRaceDecksUsed: 4,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1250,
    lastRaceDecksUsed: 12,
    lastRaceBoatAttacks: 12,
    previousRaceFame: 600,
    previousRaceDecksUsed: 4,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#20RRV9QU0",
    name: "chrisss_o5",
    role: "member",
    lastSeen: "20220721T215109.000Z",
    expLevel: 14,
    trophies: 5458,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 11,
    previousClanRank: 11,
    donations: 46,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: "-",
    lastRaceDecksUsed: "-",
    lastRaceBoatAttacks: "-",
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#URVQGJRC",
    name: "Deznorte",
    role: "elder",
    lastSeen: "20220722T115759.000Z",
    expLevel: 14,
    trophies: 5445,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 12,
    previousClanRank: 12,
    donations: 175,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 1000,
    currentRaceDecksUsed: 20,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 8,
    lastRaceFame: 1900,
    lastRaceDecksUsed: 26,
    lastRaceBoatAttacks: 16,
    previousRaceFame: 1825,
    previousRaceDecksUsed: 19,
    previousRaceBoatAttacks: 15,
  },
  {
    tag: "#90CUQUU",
    name: "PurpleDANK",
    role: "member",
    lastSeen: "20220722T110749.000Z",
    expLevel: 11,
    trophies: 5367,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 13,
    previousClanRank: 13,
    donations: 201,
    donationsReceived: 240,
    clanChestPoints: 0,
    currentRaceFame: 150,
    currentRaceDecksUsed: 2,
    currentRaceDecksUsedToday: 2,
    currentRaceBoatAttacks: 2,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 250,
    previousRaceDecksUsed: 2,
    previousRaceBoatAttacks: 2,
  },
  {
    tag: "#Y9QJYVGG",
    name: "Inesitapa",
    role: "member",
    lastSeen: "20220722T112545.000Z",
    expLevel: 11,
    trophies: 5301,
    arena: {
      id: 54000013,
      name: "Challenger II",
    },
    clanRank: 14,
    previousClanRank: 14,
    donations: 60,
    donationsReceived: 320,
    clanChestPoints: 0,
    currentRaceFame: 1350,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 800,
    lastRaceDecksUsed: 7,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1200,
    previousRaceDecksUsed: 12,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#Y8298GJ9",
    name: "ruipedrosa",
    role: "member",
    lastSeen: "20220722T104138.000Z",
    expLevel: 14,
    trophies: 5266,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 15,
    previousClanRank: 15,
    donations: 176,
    donationsReceived: 280,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 0,
    previousRaceDecksUsed: 0,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#2C2PQ0CG",
    name: "Goblin",
    role: "elder",
    lastSeen: "20220722T072613.000Z",
    expLevel: 14,
    trophies: 5248,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 16,
    previousClanRank: 16,
    donations: 16,
    donationsReceived: 40,
    clanChestPoints: 0,
    currentRaceFame: 400,
    currentRaceDecksUsed: 4,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1300,
    lastRaceDecksUsed: 8,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1900,
    previousRaceDecksUsed: 12,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#YJPUG08R2",
    name: "PedrosLow",
    role: "elder",
    lastSeen: "20220722T122807.000Z",
    expLevel: 14,
    trophies: 5204,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 17,
    previousClanRank: 17,
    donations: 244,
    donationsReceived: 280,
    clanChestPoints: 0,
    currentRaceFame: 1300,
    currentRaceDecksUsed: 15,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 2200,
    lastRaceDecksUsed: 16,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 2400,
    previousRaceDecksUsed: 18,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#82Y8G2YRR",
    name: "amxicj",
    role: "member",
    lastSeen: "20220722T130742.000Z",
    expLevel: 11,
    trophies: 5203,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 18,
    previousClanRank: 18,
    donations: 162,
    donationsReceived: 320,
    clanChestPoints: 0,
    currentRaceFame: 500,
    currentRaceDecksUsed: 10,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#8QQ2G8QCV",
    name: "Pinus",
    role: "member",
    lastSeen: "20220722T075057.000Z",
    expLevel: 12,
    trophies: 5151,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 19,
    previousClanRank: 19,
    donations: 318,
    donationsReceived: 280,
    clanChestPoints: 0,
    currentRaceFame: 700,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 400,
    lastRaceDecksUsed: 4,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#90PPRQLGG",
    name: "reinaldo 4729",
    role: "elder",
    lastSeen: "20220721T172949.000Z",
    expLevel: 12,
    trophies: 5107,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 20,
    previousClanRank: 20,
    donations: 92,
    donationsReceived: 40,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1475,
    lastRaceDecksUsed: 12,
    lastRaceBoatAttacks: 1,
    previousRaceFame: 1550,
    previousRaceDecksUsed: 12,
    previousRaceBoatAttacks: 2,
  },
  {
    tag: "#PY2P9982Y",
    name: "Sergio",
    role: "member",
    lastSeen: "20220721T180302.000Z",
    expLevel: 11,
    trophies: 5091,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 21,
    previousClanRank: 21,
    donations: 182,
    donationsReceived: 320,
    clanChestPoints: 0,
    currentRaceFame: 200,
    currentRaceDecksUsed: 5,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#2Y8P9LJGV",
    name: "SnoopKog",
    role: "member",
    lastSeen: "20220722T122333.000Z",
    expLevel: 13,
    trophies: 5042,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 22,
    previousClanRank: 22,
    donations: 10,
    donationsReceived: 80,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#2YYL8LRUV",
    name: "bernardo",
    role: "elder",
    lastSeen: "20220721T174059.000Z",
    expLevel: 13,
    trophies: 5040,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 23,
    previousClanRank: 23,
    donations: 38,
    donationsReceived: 40,
    clanChestPoints: 0,
    currentRaceFame: 500,
    currentRaceDecksUsed: 4,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 1100,
    lastRaceDecksUsed: 8,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 1850,
    previousRaceDecksUsed: 12,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#2CLLCP9J",
    name: "LastSeeker",
    role: "elder",
    lastSeen: "20220722T133430.000Z",
    expLevel: 14,
    trophies: 5028,
    arena: {
      id: 54000012,
      name: "Legendary Arena",
    },
    clanRank: 24,
    previousClanRank: 24,
    donations: 77,
    donationsReceived: 120,
    clanChestPoints: 0,
    currentRaceFame: 850,
    currentRaceDecksUsed: 8,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 8,
    lastRaceFame: 1975,
    lastRaceDecksUsed: 16,
    lastRaceBoatAttacks: 15,
    previousRaceFame: 1850,
    previousRaceDecksUsed: 16,
    previousRaceBoatAttacks: 16,
  },
  {
    tag: "#9RQ88YRGG",
    name: "scrub",
    role: "member",
    lastSeen: "20220721T191700.000Z",
    expLevel: 10,
    trophies: 4928,
    arena: {
      id: 54000056,
      name: "Arena 14",
    },
    clanRank: 25,
    previousClanRank: 25,
    donations: 44,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 1,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#8RRC0RRQ9",
    name: "OBUNGA",
    role: "member",
    lastSeen: "20220715T185427.000Z",
    expLevel: 11,
    trophies: 4764,
    arena: {
      id: 54000056,
      name: "Arena 14",
    },
    clanRank: 26,
    previousClanRank: 26,
    donations: 0,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#GJQQY8VRU",
    name: "BL_Luis",
    role: "elder",
    lastSeen: "20220722T123425.000Z",
    expLevel: 12,
    trophies: 4278,
    arena: {
      id: 54000055,
      name: "Arena 13",
    },
    clanRank: 27,
    previousClanRank: 27,
    donations: 264,
    donationsReceived: 80,
    clanChestPoints: 0,
    currentRaceFame: 1300,
    currentRaceDecksUsed: 20,
    currentRaceDecksUsedToday: 4,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 2100,
    lastRaceDecksUsed: 24,
    lastRaceBoatAttacks: 0,
    previousRaceFame: 3150,
    previousRaceDecksUsed: 27,
    previousRaceBoatAttacks: 0,
  },
  {
    tag: "#LCPVURV8L",
    name: "NaRuTo∆UChiha",
    role: "member",
    lastSeen: "20220722T091118.000Z",
    expLevel: 10,
    trophies: 4102,
    arena: {
      id: 54000011,
      name: "Arena 12",
    },
    clanRank: 28,
    previousClanRank: 28,
    donations: 18,
    donationsReceived: 40,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 0,
    lastRaceDecksUsed: 0,
    lastRaceBoatAttacks: 0,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
  {
    tag: "#JVP00GPVJ",
    name: "\\_JAQUAVIAN_/",
    role: "member",
    lastSeen: "20220715T141027.000Z",
    expLevel: 9,
    trophies: 3985,
    arena: {
      id: 54000011,
      name: "Arena 12",
    },
    clanRank: 29,
    previousClanRank: 29,
    donations: 0,
    donationsReceived: 0,
    clanChestPoints: 0,
    currentRaceFame: 0,
    currentRaceDecksUsed: 0,
    currentRaceDecksUsedToday: 0,
    currentRaceBoatAttacks: 0,
    lastRaceFame: 75,
    lastRaceDecksUsed: 1,
    lastRaceBoatAttacks: 1,
    previousRaceFame: "-",
    previousRaceDecksUsed: "-",
    previousRaceBoatAttacks: "-",
  },
];
export const filterDemo = "clanRank";
